function navigtion(){
	return '<style>'
	+'  .jumbotron {'
	+'    margin: 0 auto;'
	+'  }'
	+'  .bg {'
	+'    background-image: url("'+$.image()+'/chicago.jpg");'
	+'  }'
	+'</style>'
	+'<div class="jumbotron bg" style="padding-left: 30px;">'
	+'  <h1 style="color: white;">Welcome to Bitcamp</h1>'
	+'</div>'
	+'<nav class="navbar navbar-inverse">'
	+'      <div class="container-fluid">'
	+'        <div class="navbar-header"><div id="div-nav-list-box">'
//	+'          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" +aria-expanded="false" aria-controls="navbar">'
//	+'          <span class="sr-only">Toggle navigation</span>'
//	+'            <span class="icon-bar"></span>'
//	+'            <span class="icon-bar"></span>'
//	+'            <span class="icon-bar"></span>'
//	+'          </button>'
	+'          </div><a class="navbar-brand" href="#">'
	+'          <img src="'+$.image()+'/logo.jpg" alt="비트캠프"></a>'
	+'        </div>'
	+'        <div id="navbar" class="collapse navbar-collapse">'
	+'          <ul class="nav navbar-nav">'
	+'                    <li id="li-login">'
	+'                    </li>'
	+'            <li class="active"><a href="#">'
	+'            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;home'
	+'            </a></li>'
	+'            <li><a href="#">'
	+'              <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;QA'
	+'            </a></li>'
	+'        <!-- 드롭다운 START-->'
	+'        <li class="dropdown">'
	+'          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true" +aria-expanded="false">'
	+'            유틸리티'
	+'            <span class="caret"></span>'
	+'          </a>'
	+'          <ul id="ul-util" class="dropdown-menu">'
	+'            <li><a>롯또</a></li>'
	+'            <li><a>햄버거주문</a></li>'
	+'            <li><a>휴대폰개폰</a></li>'
	+'            <li><a>게시판</a></li>'
	+'            <li><a>글쓰기</a></li>'
	+'          </ul>'
	+'        </li>'
	+'        <!-- 드롭다운 END -->'
	+'          </ul>'
	+'        </div>'
	+'      </div>'
	+'    </nav>';
}
function createButtonNav1st(){
	return '<button id="btn-nav-list" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" +aria-expanded="false" aria-controls="navbar">'
	+'          <span class="sr-only">Toggle navigation</span>'
	+'            <span class="icon-bar"></span>'
	+'            <span class="icon-bar"></span>'
	+'            <span class="icon-bar"></span>'
	+'          </button>';
}